name: RPGCore
version: '1.0-SNAPSHOT'
main: me.ned.rpgCore.RPGCore
api-version: '1.21'
commands:
  woodcutting:
    description: 'Shows your woodcutting stats'
    usage: /woodcutting
  mining:
    description: 'Shows your mining stats'
    usage: /mining